version: '3.8'

services:
  app:
    build:
      context: ./app
    container_name: rag_app
    volumes:
      - ./app:/app
    ports:
      - "8888:8888"  # Jupyter Notebook
      - "7860:7860"  # Gradio port
      - "8237:8237"  # ZenML port
    depends_on:
      - mongodb
      - qdrant
    environment:
      - PYTHONUNBUFFERED=1
          # Point the app to Ollama inside docker network
      - OLLAMA_HOST=http://host.docker.internal:11434
    command: bash -c "jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "ollama:host-gateway"

  mongodb:
    image: mongo:latest
    container_name: rag_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  qdrant:
    image: qdrant/qdrant
    container_name: rag_qdrant
    ports:
      - "6333:6333"

volumes:
  mongodb_data:
  ollama_data:
